---
- name: Setup UMIG Local Development Environment
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    project_dir: "{{ playbook_dir }}"
    scriptrunner_jar_path: "{{ project_dir }}/confluence/"

  tasks:
    - name: Check if .env file exists
      stat:
        path: "{{ project_dir }}/.env"
      register: env_file

    - name: Fail if .env file is missing
      fail:
        msg: "The '.env' file is missing. Please copy '.env.example' to '.env' and fill in the required values before running this playbook."
      when: not env_file.stat.exists


    - name: Build and start the containerized services
      command: podman-compose up -d --build --no-cache
      args:
        chdir: "{{ project_dir }}"
      register: compose_up
      changed_when: "'Creating' in compose_up.stdout or 'Recreating' in compose_up.stdout"

    - name: Display final instructions
      debug:
        msg:
          - "Development environment started successfully."
          - "Confluence should be available at: http://localhost:8090"
          - "PostgreSQL is running on port: 5432"
          - "MailHog (SMTP mock) UI is at: http://localhost:8025"