#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${UMIG_DB_USER} WITH PASSWORD '${UMIG_DB_PASSWORD}';
    CREATE DATABASE ${UMIG_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${UMIG_DB_NAME} TO ${UMIG_DB_USER};
EOSQL
