-- liquibase formatted sql

-- changeset lucas.challamel:009_create_stg_import_tables author:Franck Desmeuzes
-- comment: Création du type ENUM et des tables de staging pour l'import

CREATE TYPE stg_step_type AS ENUM ('IGO', 'CHK', 'DUM', 'TRT');

CREATE TABLE stg_steps (
    id VARCHAR(255) PRIMARY KEY,
    step_type stg_step_type,
    step_number INT,
    step_title TEXT,
    step_predecessor VARCHAR(255),
    step_successor VARCHAR(255),
    step_assigned_team VARCHAR(255),
    step_impacted_teams VARCHAR(255),
    step_macro_time_sequence TEXT,
    step_time_sequence TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE stg_step_instructions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id VARCHAR(255) NOT NULL,
    instruction_id TEXT NOT NULL,
    instruction_text TEXT,
    instruction_assignee VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_stg_step
        FOREIGN KEY(step_id)
        REFERENCES stg_steps(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE stg_steps IS 'Staging: informations principales de chaque step importée (Confluence JSON).';
COMMENT ON TABLE stg_step_instructions IS 'Staging: instructions détaillées pour chaque step.';

--rollback DROP TABLE IF EXISTS stg_step_instructions;
--rollback DROP TABLE IF EXISTS stg_steps;
--rollback DROP TYPE IF EXISTS stg_step_type;
